image: Visual Studio 2017
configuration:
  - Release
platform:
  - x86
  - x64
# cache:
#   # Cache Nuget packages in "packages" folder. Break cache if "packages.config" is updated.
#   - packages -> **\packages.config
# before_build: nuget restore
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build:
  project: OP2MapImager.sln
