version: 2
jobs:
  build:
    docker:
      - image: outpostuniverse/circleci-gcc-googletest-freeimage
    steps:
      - checkout
      - run: git submodule update --init
      - run: make --keep-going
      - run: make check
